CREATE TABLE IF NOT EXISTS `SHUDSettings` (
  `identifier` varchar(250)  COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `index` int(11) NOT NULL AUTO_INCREMENT,
  `hud2` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hud` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notifys` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `speedometer` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `eatdrink` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL, 
  `weaponinfo` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bankinfo` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interaction` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `voicedesign` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL, 
  `textdesign` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iddesign` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `progressbar` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iddesignleftright`int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bankinfoleftright`int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `voicedesignleftright`int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weaponinfoleftright`int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hudleftright` int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notifysleftright`int(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hud2coords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hudcoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notifyscoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `speedometercoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `eatdrinkcoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL, 
  `weaponinfocoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bankinfocoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interactioncoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `voicedesigncoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,   
  `adminotifycoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL, 
  `textdesigncoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iddesigncoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `progressbarcoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `chatcoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `jobcoords` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`identifier`) USING BTREE,
  KEY `index` (`index`)
) ENGINE=InnoDB AUTO_INCREMENT=346 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;